export interface ProjectMetrics {
  teamSize: number;
  launchMonths: number;
  budgetMin: string;
  budgetMax: string;
  targetClients: string;
  totalArticles: string;
  mrr: string;
}

export function extractMetricsFromDocs(): ProjectMetrics {
  return {
    teamSize: 10,
    launchMonths: 4,
    budgetMin: '390,000',
    budgetMax: '504,000',
    targetClients: '30-40',
    totalArticles: '100+',
    mrr: '45,000-80,000',
  };
}

export interface TimelinePhase {
  month: number;
  title: string;
  focus: string;
  teamSize: number;
  articles: number;
  clients: number;
  mrr: string;
}

export function getTimelinePhases(): TimelinePhase[] {
  return [
    {
      month: 1,
      title: 'التأسيس',
      focus: 'Foundation',
      teamSize: 4,
      articles: 10,
      clients: 0,
      mrr: '0',
    },
    {
      month: 2,
      title: 'التطوير',
      focus: 'Development',
      teamSize: 7,
      articles: 30,
      clients: 0,
      mrr: '0',
    },
    {
      month: 3,
      title: 'البيتا',
      focus: 'Beta',
      teamSize: 10,
      articles: 70,
      clients: 7,
      mrr: '10-15K',
    },
    {
      month: 4,
      title: 'الإطلاق',
      focus: 'Launch',
      teamSize: 10,
      articles: 100,
      clients: 35,
      mrr: '50-80K',
    },
  ];
}

export interface Position {
  title: string;
  titleEn: string;
  count: number;
  salaryMin: number;
  salaryMax: number;
  phase: number;
  requirements: string[];
  requirementsEn: string[];
  employmentType?: 'full-time' | 'project-based';
  filledBy?: string;
}

type PositionAliasMaps = {
  aliasToCanonical: Map<string, string>;
  canonicalToAliases: Map<string, string[]>;
};

let cachedPositionAliasMaps: PositionAliasMaps | null = null;

function buildPositionAliasMaps(): PositionAliasMaps {
  const aliasToCanonical = new Map<string, string>();
  const canonicalToAliases = new Map<string, string[]>();

  getTeamPositions().forEach((position) => {
    const aliases = Array.from(new Set([position.titleEn, position.title]));
    canonicalToAliases.set(position.titleEn, aliases);
    aliases.forEach((alias) => {
      aliasToCanonical.set(alias, position.titleEn);
    });
  });

  return {
    aliasToCanonical,
    canonicalToAliases,
  };
}

function getPositionAliasMaps(): PositionAliasMaps {
  if (!cachedPositionAliasMaps) {
    cachedPositionAliasMaps = buildPositionAliasMaps();
  }
  return cachedPositionAliasMaps;
}

export function getCanonicalPositionTitle(position: string): string {
  const { aliasToCanonical } = getPositionAliasMaps();
  return aliasToCanonical.get(position) ?? position;
}

export function getPositionAliases(position: string): string[] {
  const { aliasToCanonical, canonicalToAliases } = getPositionAliasMaps();
  const canonical = aliasToCanonical.get(position) ?? position;
  return canonicalToAliases.get(canonical) ?? [canonical];
}

export function getTeamPositions(): Position[] {
  return [
    // ========== LEADERSHIP & EXECUTIVE (Phase 0) ==========
    {
      title: 'CTO / Technical Lead',
      titleEn: 'CTO / Technical Lead',
      count: 1,
      salaryMin: 0,
      salaryMax: 0,
      phase: 0,
      filledBy: 'المهندس خالد',
      requirements: [
        '8-10 سنوات خبرة في هندسة البرمجيات',
        'خبرة مؤكدة في بناء وإطلاق منتجات SaaS',
        'معماري Full-stack: React/Next.js، Node.js',
        'إتقان متقدم: TypeScript، shadcn/ui، Tailwind CSS، CSS، JavaScript، JSON',
        'إدارة الحالة: Redux، Zustand، Context API',
        'Server-Side Rendering (SSR/SSG) مع Next.js',
        'Responsive Design و Mobile-First approach',
        'تحسين أداء الويب و Progressive Web Apps (PWA)',
        'تصميم وتنفيذ RESTful APIs و GraphQL',
        'المصادقة والتفويض: JWT، OAuth، Session Management',
        'أمان APIs وأفضل الممارسات الأمنية',
        'Serverless Architecture و WebSockets',
        'Git و CI/CD: GitHub Actions، GitLab CI',
        'تكامل APIs الطرف الثالث',
        'إدارة الوسائط السحابية: Cloudinary',
        'تحسين محركات البحث (SEO) وإمكانية الوصول (WCAG)',
        'System Design، Microservices، Scalability',
        'خبرة عملية في AI/ML APIs (OpenAI، Anthropic)',
        'قواعد البيانات SQL و NoSQL - مستوى متقدم',
        'مهارات متقدمة في حل المشكلات والتصحيح (Problem Solving & Debugging)',
        'قيادة وإدارة فرق التطوير التقنية',
        'Product mindset، Agile Leadership',
        'رؤية استراتيجية تقنية وقدرة على اتخاذ القرارات',
        'فهم عميق للسوق السعودي والعربي'
      ],
      requirementsEn: [
        '8-10 years software engineering experience',
        'Proven track record building and launching SaaS products',
        'Full-stack architect: React/Next.js, Node.js',
        'Expert proficiency: TypeScript, shadcn/ui, Tailwind CSS, CSS, JavaScript, JSON',
        'State Management: Redux, Zustand, Context API',
        'Server-Side Rendering (SSR/SSG) with Next.js',
        'Responsive Design & Mobile-First approach',
        'Web Performance Optimization & Progressive Web Apps (PWA)',
        'RESTful APIs & GraphQL design and implementation',
        'Authentication & Authorization: JWT, OAuth, Session Management',
        'API Security & Best Practices',
        'Serverless Architecture & WebSockets',
        'Git & CI/CD: GitHub Actions, GitLab CI',
        'Third-party API integrations',
        'Cloud media management: Cloudinary',
        'SEO optimization & Accessibility (WCAG standards)',
        'System Design, Microservices, Scalability',
        'Hands-on AI/ML APIs (OpenAI, Anthropic)',
        'SQL and NoSQL databases - Advanced level',
        'Advanced problem solving and debugging skills',
        'Leading and managing technical development teams',
        'Product mindset, Agile Leadership',
        'Strategic technical vision and decision-making ability',
        'Deep understanding of Saudi/Arab market'
      ]
    },
    {
      title: 'Operations',
      titleEn: 'Operations',
      count: 1,
      salaryMin: 0,
      salaryMax: 0,
      phase: 0,
      filledBy: 'المهندس عبدالعزيز',
      requirements: [
        '5+ سنوات خبرة في إدارة العمليات التقنية',
        'خبرة في تنسيق فرق متعددة (تسويق، محتوى، مبيعات)',
        'إدارة وتدريب فرق مبيعات 3-5 أشخاص',
        'فهم عميق لدورة مبيعات SaaS',
        'خبرة في السوق السعودي وأصحاب المتاجر',
        'إدارة العمليات اليومية والـ workflows',
        'خبرة في project management tools',
        'مهارات تحليلية لتحسين الكفاءة',
        'معرفة بـ Process Optimization',
        'مهارات تفاوض وإغلاق صفقات',
        'القدرة على حل المشاكل بسرعة',
        'مهارات تواصل وتنظيم ممتازة',
        'خبرة في إدارة الدعم الفني والعملاء',
        'إدارة فريق الدعم وتذاكر العملاء',
        'مهارات تحليل البيانات والتقارير',
        'معرفة بـ Google Analytics، Excel متقدم',
        'تحليل سلوك المستخدمين و Conversion Funnels',
        'معرفة بـ Data Visualization',
        'إتقان العربية والإنجليزية'
      ],
      requirementsEn: [
        '5+ years operations management in tech',
        'Experience coordinating multi-teams (marketing, content, sales)',
        'Managed and trained sales teams of 3-5',
        'Deep understanding of SaaS sales cycle',
        'Experience in Saudi market with e-commerce owners',
        'Daily operations and workflow management',
        'Project management tools experience',
        'Analytical skills for efficiency optimization',
        'Process Optimization knowledge',
        'Negotiation and deal closing skills',
        'Quick problem-solving ability',
        'Excellent communication and organization',
        'Customer support and service management experience',
        'Support team and ticket management',
        'Data analysis and reporting skills',
        'Knowledge of Google Analytics, Advanced Excel',
        'User behavior analysis & Conversion Funnels',
        'Data Visualization knowledge',
        'Fluent in Arabic and English'
      ]
    },
    {
      title: 'HR Manager',
      titleEn: 'HR Manager',
      count: 1,
      salaryMin: 0,
      salaryMax: 0,
      phase: 0,
      requirements: [
        '5+ سنوات خبرة في إدارة الموارد البشرية',
        'خبرة في بناء سياسات وأنظمة الموارد البشرية لشركات تقنية أو SaaS',
        'إدارة عمليات التوظيف، التقييم، والتطوير الوظيفي',
        'خبرة في بناء ثقافة عمل صحية وتحسين رضا الموظفين',
        'إتقان العربية والإنجليزية'
      ],
      requirementsEn: [
        '5+ years experience in HR management',
        'Experience building HR policies and systems for tech or SaaS companies',
        'Manage hiring, performance reviews, and career development',
        'Experience building healthy culture and improving employee satisfaction',
        'Fluent in Arabic and English'
      ]
    },
    {
      title: 'Talent Acquisition Specialist',
      titleEn: 'Talent Acquisition Specialist',
      count: 1,
      salaryMin: 0,
      salaryMax: 0,
      phase: 0,
      requirements: [
        '3+ سنوات خبرة في التوظيف الفني أو التوظيف لشركات تقنية',
        'خبرة في إدارة قمع التوظيف من مرحلة الترشيح حتى التوظيف',
        'قدرة عالية على تقييم المرشحين وبناء علاقات طويلة المدى معهم',
        'إتقان أدوات التوظيف والمنصات الرقمية',
        'إتقان العربية والإنجليزية'
      ],
      requirementsEn: [
        '3+ years experience in technical or tech hiring',
        'Experience managing the full hiring funnel from sourcing to offer',
        'Strong ability to assess candidates and build long-term relationships',
        'Proficiency with recruiting tools and digital platforms',
        'Fluent in Arabic and English'
      ]
    },
    {
      title: 'Finance Manager',
      titleEn: 'Finance Manager',
      count: 1,
      salaryMin: 0,
      salaryMax: 0,
      phase: 0,
      requirements: [
        '5+ سنوات خبرة في الإدارة المالية أو المحاسبة المتقدمة',
        'خبرة في إعداد الميزانيات، التدفقات النقدية، والتقارير المالية',
        'فهم جيد لنماذج الإيرادات والتكاليف لشركات SaaS',
        'خبرة في العمل مع المدققين الخارجيين والبنوك',
        'إتقان العربية والإنجليزية'
      ],
      requirementsEn: [
        '5+ years experience in financial management or advanced accounting',
        'Experience preparing budgets, cash flow, and financial reports',
        'Good understanding of SaaS revenue and cost models',
        'Experience working with external auditors and banks',
        'Fluent in Arabic and English'
      ]
    },
    {
      title: 'Accountant',
      titleEn: 'Accountant',
      count: 1,
      salaryMin: 0,
      salaryMax: 0,
      phase: 0,
      requirements: [
        '3+ سنوات خبرة في المحاسبة',
        'إتقان إعداد القيود اليومية والتسويات البنكية',
        'خبرة في أنظمة المحاسبة السحابية',
        'فهم جيد للضرائب والالتزامات المالية في السعودية',
        'إتقان العربية والإنجليزية'
      ],
      requirementsEn: [
        '3+ years experience in accounting',
        'Strong in journal entries and bank reconciliations',
        'Experience with cloud accounting systems',
        'Good understanding of tax and financial obligations in Saudi Arabia',
        'Fluent in Arabic and English'
      ]
    },
    {
      title: 'Head of Content / SEO Specialist',
      titleEn: 'Head of Content / SEO Specialist',
      count: 1,
      salaryMin: 0,
      salaryMax: 0,
      phase: 0,
      employmentType: 'full-time',
      requirements: [
        '--- المتطلبات والخبرات ---',
        '3+ سنوات خبرة عملية في إدارة المحتوى وتحسين محركات البحث (SEO)',
        'قيادة وإدارة فرق محتوى (5-10 أشخاص) شاملة المستقلين والوكالات',
        'بناء وتنفيذ استراتيجيات محتوى شاملة متوافقة مع خطة النمو',
        'فهم عميق لخوارزميات Google ومفاهيم Technical SEO',
        '',
        '--- إتقان أدوات Google الأساسية ---',
        'Google Analytics 4 (GA4): تتبع وتحليل سلوك المستخدمين وتقارير متقدمة',
        'Google Search Console: مراقبة الأداء العضوي وإصلاح المشاكل التقنية',
        'Google Tag Manager (GTM): إدارة Tags والتتبع بدون برمجة',
        'Google Data Studio / Looker Studio: بناء Dashboards وتقارير بصرية',
        'Google Merchant Center: إدارة بيانات المنتجات للتجارة الإلكترونية',
        'Google Ads: فهم الإعلانات المدفوعة وتحليل الأداء',
        'Google Optimize: اختبارات A/B وتحسين معدلات التحويل',
        'Google My Business: إدارة وتحسين الظهور المحلي',
        '',
        '--- المهارات الأساسية الأخرى ---',
        'خبرة في Link Building واستراتيجيات بناء Domain Authority',
        'تحليل المنافسين، بحث الكلمات المفتاحية، وتحديد فرص النمو',
        'إنشاء محتوى متعدد الأشكال (مقالات، فيديو، بودكاست، ويبينارز)',
        'مهارات Copywriting وStorytelling تعزز التفاعل والتحويل',
        'إتقان WordPress ومنصات التجارة (Salla، Zid، Shopify)',
        'إدارة التقويم التحريري وسير العمل بشكل منهجي',
        'إتقان أدوات SEO: SEMrush، Ahrefs، SurferSEO',
        'خبرة في تحسين المحتوى العربي ورفع الترتيب العضوي',
        'فهم عميق للسوق السعودي والخليجي وسلوك المستخدم الرقمي',
        'إتقان استثنائي للعربية والإنجليزية كتابةً وتحريرًا',
        '',
        '--- مهام ومسؤوليات إضافية ---',
        'تطوير استراتيجية النمو بالمحتوى وربطها بالأهداف التسويقية',
        'تأسيس أنظمة محتوى قابلة للتوسع (دليل الأسلوب، نبرة العلامة، Authority)',
        'تحديد ومتابعة KPIs لقياس أداء المحتوى و ROI',
        'استخدام أدوات AI (ChatGPT، Jasper) لتحسين كفاءة الإنتاج',
        'تطبيق اختبارات A/B لتحسين التجربة ومعدلات التحويل',
        'بناء استراتيجيات توزيع المحتوى (نشرات، سوشيال ميديا، PR، شراكات)',
        'توجيه الفريق ورفع الكفاءة بالتدريب المستمر',
        'ضمان اتساق الهوية والرسائل عبر جميع القنوات',
        'التعاون مع فرق المنتج والتسويق والمبيعات لتحقيق أهداف النمو',
        'تقديم تقارير استراتيجية شاملة للإدارة العليا',
        '',
        '--- ميزات إضافية (Plus Points) ---',
        '⭐ خبرة في SaaS Content Strategy أو E-commerce SEO',
        '⭐ معرفة عملية بـ Structured Data وMicroservices SEO',
        '⭐ خبرة في أدوات AI وContent Automation',
        '⭐ مهارات تحليل بيانات متقدمة (Looker Studio / Data Studio)'
      ],
      requirementsEn: [
        '--- Requirements & Experience ---',
        '3+ years hands-on content management and SEO expertise',
        'Lead content teams (5-10 members) including freelancers and agencies',
        'Build and execute comprehensive content strategies aligned with growth plans',
        'Deep understanding of Google algorithms and Technical SEO',
        '',
        '--- Master Google Tools Suite ---',
        'Google Analytics 4 (GA4): Advanced user behavior tracking and reporting',
        'Google Search Console: Organic performance monitoring and technical issue resolution',
        'Google Tag Manager (GTM): Tag and tracking management without coding',
        'Google Data Studio / Looker Studio: Build visual dashboards and reports',
        'Google Merchant Center: Product data management for e-commerce',
        'Google Ads: Understanding paid advertising and performance analysis',
        'Google Optimize: A/B testing and conversion rate optimization',
        'Google My Business: Local presence management and optimization',
        '',
        '--- Other Core Skills ---',
        'Link Building experience and Domain Authority optimization',
        'Competitor analysis, keyword research, and growth opportunity identification',
        'Create multi-format content (articles, videos, podcasts, webinars)',
        'Advanced Copywriting and Storytelling driving engagement and conversion',
        'Expert in WordPress and e-commerce platforms (Salla, Zid, Shopify)',
        'Systematic editorial calendar and workflow management',
        'Master SEO tools: SEMrush, Ahrefs, SurferSEO',
        'Arabic content optimization and organic ranking improvement',
        'Deep understanding of Saudi/GCC markets and digital user behavior',
        'Exceptional Arabic and English writing and editing proficiency',
        '',
        '--- Additional Responsibilities ---',
        'Develop content growth strategy aligned with marketing objectives',
        'Establish scalable content systems (style guide, brand voice, authority)',
        'Define and track KPIs to measure content performance and ROI',
        'Leverage AI tools (ChatGPT, Jasper) to boost production efficiency',
        'Implement A/B testing to optimize experience and conversion rates',
        'Build distribution strategies (newsletters, social media, PR, partnerships)',
        'Guide team and elevate capabilities through continuous training',
        'Ensure brand consistency across all content and channels',
        'Collaborate with product, marketing, and sales teams for growth goals',
        'Deliver comprehensive strategic reports to senior management',
        '',
        '--- Plus Points ---',
        '⭐ SaaS Content Strategy or E-commerce SEO experience',
        '⭐ Practical knowledge of Structured Data and Microservices SEO',
        '⭐ AI tools and Content Automation experience',
        '⭐ Advanced data analysis skills (Looker Studio / Data Studio)'
      ]
    },
    {
      title: 'Head of Marketing',
      titleEn: 'Head of Marketing',
      count: 1,
      salaryMin: 0,
      salaryMax: 0,
      phase: 0,
      employmentType: 'full-time',
      requirements: [
        '--- المؤهلات والخبرة ---',
        '3+ سنوات خبرة عملية في التسويق الرقمي',
        'خبرة مؤكدة في تسويق منتجات SaaS أو B2B',
        'فهم عميق لمفاهيم CAC، LTV، ROI ومقاييس النمو',
        'إجادة استخدام أدوات التسويق الآلي: HubSpot، Marketo، ActiveCampaign',
        'مهارات تحليل بيانات عالية واتخاذ قرارات مبنية على الأرقام',
        'خبرة في Product Marketing وContent Marketing',
        'خبرة في Brand Management وبناء الصورة الذهنية للعلامة التجارية',
        'مهارات قوية في الكتابة التسويقية والإبداعية بالعربية والإنجليزية',
        'معرفة متقدمة بثقافة المحتوى العربي والسوق السعودي',
        '',
        '--- المسؤوليات الرئيسية ---',
        'قيادة وتنفيذ استراتيجية التسويق الشاملة عبر القنوات الرقمية وغير الرقمية',
        'تطوير وتنفيذ حملات Growth Marketing لزيادة العملاء وتحسين الأداء',
        'إدارة الميزانيات التسويقية بفعالية وتحقيق أفضل ROI',
        'إدارة فريق التسويق وتحفيزه لتحقيق الأهداف الاستراتيجية',
        'تطوير هوية العلامة التجارية وضمان تناسق الرسائل التسويقية',
        'الإشراف على الحملات الإعلانية في Google Ads وMeta Ads وLinkedIn Ads',
        'تطبيق استراتيجيات SEO/SEM وتحسين الظهور في محركات البحث',
        'تطوير وتنفيذ حملات Email Marketing وDrip Campaigns',
        'تحليل الأداء باستخدام Google Analytics، Mixpanel، Amplitude، SEMrush',
        'إجراء A/B Testing وتحسين معدلات التحويل (CRO)',
        'قيادة مبادرات Product Marketing بالتعاون مع فرق المنتج والمبيعات',
        'إدارة استراتيجيات Social Media على Twitter/X، LinkedIn، Instagram، TikTok',
        'إنشاء محتوى تسويقي جذاب (نصوص، صور، فيديو)',
        'التعاون مع فرق المبيعات وخدمة العملاء وتطوير المنتج',
        'متابعة المنافسين وتحليل السوق السعودي لتوجيه القرارات التسويقية',
        '',
        '--- ميزات إضافية ---',
        '⭐ إجادة استخدام أدوات التصميم مثل Canva وAdobe Suite'
      ],
      requirementsEn: [
        '--- Qualifications & Experience ---',
        '3+ years hands-on digital marketing experience',
        'Proven track record marketing SaaS or B2B products',
        'Deep understanding of CAC, LTV, ROI and growth metrics',
        'Proficiency in marketing automation tools: HubSpot, Marketo, ActiveCampaign',
        'Strong data analysis skills and data-driven decision making',
        'Product Marketing and Content Marketing experience',
        'Brand Management and brand image building experience',
        'Strong marketing and creative writing skills in Arabic and English',
        'Advanced knowledge of Arabic content culture and Saudi market',
        '',
        '--- Key Responsibilities ---',
        'Lead and execute comprehensive marketing strategy across digital and non-digital channels',
        'Develop and implement Growth Marketing campaigns to increase customers and improve performance',
        'Manage marketing budgets effectively and achieve best ROI',
        'Manage and motivate marketing team to achieve strategic goals',
        'Develop brand identity and ensure marketing message consistency',
        'Oversee advertising campaigns on Google Ads, Meta Ads, and LinkedIn Ads',
        'Implement SEO/SEM strategies and improve search engine visibility',
        'Develop and execute Email Marketing and Drip Campaigns',
        'Analyze performance using Google Analytics, Mixpanel, Amplitude, SEMrush',
        'Conduct A/B Testing and Conversion Rate Optimization (CRO)',
        'Lead Product Marketing initiatives in collaboration with product and sales teams',
        'Manage Social Media strategies on Twitter/X, LinkedIn, Instagram, TikTok',
        'Create engaging marketing content (text, images, video)',
        'Collaborate with sales, customer service, and product development teams',
        'Monitor competitors and analyze Saudi market to guide marketing decisions',
        '',
        '--- Plus Points ---',
        '⭐ Proficiency in design tools like Canva and Adobe Suite',
        '⭐ Strong network in Saudi market'
      ]
    },

    // ========== TECHNICAL TEAM (Phase 1) ==========
    {
      title: 'Frontend Developer',
      titleEn: 'Frontend Developer',
      count: 1,
      salaryMin: 0,
      salaryMax: 0,
      phase: 1,
      filledBy: 'المهندس محمد',
      requirements: [
        '3-5 سنوات خبرة عملية في تطوير واجهات المستخدم',
        'React.js/Next.js 14+، TypeScript متقدم',
        'Tailwind CSS، Responsive Design، Mobile-First',
        'State Management: Redux، Zustand، أو Context API',
        'RESTful APIs integration، fetch/axios',
        'Performance optimization، Web Vitals',
        'Git، CI/CD أساسيات',
        'خبرة في دعم اللغة العربية و RTL layouts',
        'Agile/Scrum، قدرة على العمل الجماعي'
      ],
      requirementsEn: [
        '3-5 years hands-on Frontend development experience',
        'React.js/Next.js 14+, Advanced TypeScript',
        'Tailwind CSS, Responsive Design, Mobile-First approach',
        'State Management: Redux, Zustand, or Context API',
        'RESTful APIs integration, fetch/axios',
        'Performance optimization, Web Vitals',
        'Git, CI/CD fundamentals',
        'Experience supporting Arabic language & RTL layouts',
        'Agile/Scrum, Strong teamwork skills'
      ]
    },
    {
      title: 'Backend Developer',
      titleEn: 'Backend Developer',
      count: 1,
      salaryMin: 0,
      salaryMax: 0,
      phase: 1,
      filledBy: 'المهندس مصطفى',
      requirements: [
        '5-7 سنوات خبرة في Backend Development',
        'إتقان Node.js + Express/Fastify أو NestJS',
        'خبرة قوية في قواعد البيانات: PostgreSQL، MySQL، MongoDB',
        'خبرة في Prisma ORM أو TypeORM',
        'معرفة عميقة بـ REST APIs، GraphQL، و Microservices',
        'Authentication: JWT, OAuth, Session Management',
        'Payment integrations (Stripe, Paddle)',
        'Caching strategies (Redis, Memcached)',
        'Docker و CI/CD: GitHub Actions أساسيات',
        'إدارة قواعد البيانات، Backups، Migrations',
        'Security best practices و OWASP',
        'قيادة ومراجعة كود المطورين'
      ],
      requirementsEn: [
        '5-7 years Backend Development experience',
        'Expert Node.js + Express/Fastify or NestJS',
        'Strong database experience: PostgreSQL, MySQL, MongoDB',
        'Experience with Prisma ORM or TypeORM',
        'Deep knowledge of REST APIs, GraphQL, and Microservices',
        'Authentication: JWT, OAuth, Session Management',
        'Payment integrations (Stripe, Paddle)',
        'Caching strategies (Redis, Memcached)',
        'Docker & CI/CD: GitHub Actions fundamentals',
        'Database management, Backups, Migrations',
        'Security best practices & OWASP',
        'Code reviews and team leadership'
      ]
    },
    {
      title: 'React Native Developer',
      titleEn: 'React Native Developer',
      count: 1,
      salaryMin: 0,
      salaryMax: 0,
      phase: 1,
      employmentType: 'full-time',
      requirements: [
        '--- المؤهلات والخبرة ---',
        '3-4 سنوات خبرة عملية في React Native (v0.70+)',
        'إتقان TypeScript وJavaScript (ES6+)',
        'سجل مثبت في نشر تطبيقات ناجحة على App Store وGoogle Play',
        'فهم عميق لـ React Native Architecture، Navigation، Lifecycle',
        'خبرة عملية في التكامل مع الأنظمة الخلفية عبر RESTful APIs',
        'إتقان العمل مع WhatsApp Cloud API والتكامل الكامل معها',
        'إجادة العمل مع Next.js أو React.js (ميزة تنافسية قوية)',
        'خبرة في CI/CD Pipelines لتطبيقات الموبايل',
        'مهارات قوية في حل المشكلات وتصحيح الأخطاء',
        'خبرة في العمل ضمن بيئة Agile/Scrum',
        'إتقان العمل الجماعي ومراجعة الكود ضمن فرق متعددة الاختصاصات',
        '',
        '--- المسؤوليات ---',
        'تطوير وصيانة تطبيقات موبايل باستخدام React Native (v0.70+)',
        'كتابة كود نظيف، منظم، وقابل لإعادة الاستخدام باستخدام TypeScript',
        'تصميم وتنفيذ واجهات تفاعلية وسلسة',
        'التكامل مع RESTful APIs وإدارة البيانات المحلية عبر Async Storage',
        'إعداد وإدارة Push Notifications وبيانات التطبيق في وضع عدم الاتصال',
        'تحسين الأداء وإدارة الذاكرة لضمان تجربة مستخدم مثالية',
        'إنشاء وبناء ونشر التطبيقات على App Store وGoogle Play',
        'التكامل مع Native Modules لـ iOS (Swift/Objective-C) و Android (Kotlin/Java)',
        'تطبيق أنماط State Management مثل Redux، Zustand، أو Context API',
        'المساهمة في تصميم وتحسين البنية المعمارية للتطبيق',
        'إدارة ومراجعة الكود عبر Git وعمليات الـ Pull Requests',
        'استخدام أدوات CI/CD مثل Fastlane، App Center، CodePush',
        'التعاون مع فرق التصميم والمنتج والـ Backend لتنفيذ الميزات بدقة',
        'دعم اللغة العربية والاتجاه من اليمين إلى اليسار (RTL) بشكل متكامل',
        '',
        '--- ميزات إضافية ---',
        '⭐ معرفة بـ GraphQL أو WebSockets',
        '⭐ خبرة في أدوات التحليل والأداء مثل Firebase Analytics، Sentry، A/B Testing',
        '⭐ خبرة في تطوير تجربة مستخدم High-Performance UX/UI',
        '⭐ معرفة بتصميم الأنظمة متعددة اللغات',
        '⭐ شغف بالتعلم المستمر ومتابعة أحدث اتجاهات تطوير الموبايل'
      ],
      requirementsEn: [
        '--- Qualifications & Experience ---',
        '3-4 years hands-on React Native experience (v0.70+)',
        'Master TypeScript and JavaScript (ES6+)',
        'Proven track record publishing successful apps to App Store & Google Play',
        'Deep understanding of React Native Architecture, Navigation, Lifecycle',
        'Hands-on experience integrating with backend systems via RESTful APIs',
        'Expert knowledge of WhatsApp Cloud API and full integration capabilities',
        'Proficiency in Next.js or React.js (strong competitive advantage)',
        'Experience with CI/CD Pipelines for mobile apps',
        'Strong problem-solving and debugging skills',
        'Experience working in Agile/Scrum environment',
        'Team collaboration and code review expertise in cross-functional teams',
        '',
        '--- Responsibilities ---',
        'Develop and maintain mobile apps using React Native (v0.70+)',
        'Write clean, organized, reusable code using TypeScript',
        'Design and implement interactive, smooth interfaces',
        'Integrate with RESTful APIs and manage local data via Async Storage',
        'Set up and manage Push Notifications and offline app data',
        'Optimize performance and memory management for optimal user experience',
        'Build and deploy apps to App Store and Google Play',
        'Integrate with Native Modules for iOS (Swift/Objective-C) and Android (Kotlin/Java)',
        'Implement State Management patterns like Redux, Zustand, or Context API',
        'Contribute to app architecture design and optimization',
        'Manage and review code via Git and Pull Request workflows',
        'Use CI/CD tools like Fastlane, App Center, CodePush',
        'Collaborate with design, product, and backend teams to implement features accurately',
        'Full support for Arabic language and Right-to-Left (RTL) direction',
        '',
        '--- Plus Points ---',
        '⭐ Knowledge of GraphQL or WebSockets',
        '⭐ Experience with analytics and performance tools like Firebase Analytics, Sentry, A/B Testing',
        '⭐ Experience developing High-Performance UX/UI',
        '⭐ Knowledge of multi-language system design',
        '⭐ Passion for continuous learning and following latest mobile development trends'
      ]
    },
    {
      title: 'Designer',
      titleEn: 'Designer',
      count: 1,
      salaryMin: 0,
      salaryMax: 0,
      phase: 1,
      filledBy: 'المهندس احمد',
      requirements: [
        '4+ سنوات خبرة احترافية في التصميم الرقمي والاتصال البصري',
        'إتقان كامل لـ Adobe Creative Suite (Photoshop، Illustrator، After Effects)',
        'إتقان Figma لتصميم واجهات المستخدم والتعاون',
        'خبرة مثبتة في تطوير هويات بصرية رقمية متكاملة (شعارات، أدلة علامة تجارية)',
        'مهارة في تصميم محتوى وسائل التواصل الاجتماعي والإعلانات الرقمية',
        'خبرة في تصميم أصول UI/UX للويب والتطبيقات (أيقونات، رسوم توضيحية، رسومات واجهة)',
        'القدرة على إنتاج Motion Graphics ورسوم متحركة بسيطة',
        'فهم عميق لمبادئ التصميم الرقمي، نظرية الألوان، التكوين، والطباعة',
        'مفكر مبدع بقدرة على ترجمة المفاهيم إلى تصاميم رقمية مؤثرة',
        'Portfolio رقمي قوي يُظهر مشاريع ويب، موبايل، ووسائل تواصل اجتماعي',
        'القدرة على العمل بفعالية ضمن فريق إبداعي والتنسيق مع فرق التسويق والتطوير',
        'اهتمام ممتاز بالتفاصيل، إدارة الوقت، والقدرة على التكيف تحت المواعيد النهائية',
        'مهارات تواصل قوية وانفتاح على التغذية الراجعة البناءة',
        'خبرة في دعم اللغة العربية والتصميم بنمط RTL (اليمين إلى اليسار)'
      ],
      requirementsEn: [
        '4+ years professional experience in digital design and visual communication',
        'Strong command of Adobe Creative Suite (Photoshop, Illustrator, After Effects)',
        'Proficiency in Figma for UI design and collaboration',
        'Proven experience developing complete digital visual identities (logos, brand guidelines)',
        'Skilled in designing social media content and digital advertising visuals',
        'Experience designing UI/UX assets for web and mobile apps (icons, illustrations, interface graphics)',
        'Ability to produce motion graphics and simple animations',
        'Deep understanding of digital design principles, color theory, composition, and typography',
        'Creative thinker with ability to translate concepts into impactful digital visuals',
        'Strong digital portfolio demonstrating web, mobile, and social media projects',
        'Ability to work effectively within creative team and coordinate with marketing and development teams',
        'Excellent attention to detail, time management, and adaptability under deadlines',
        'Strong communication skills and openness to constructive feedback',
        'Experience supporting Arabic language and RTL (Right-to-Left) design layouts'
      ]
    },
    {
      title: 'UI/UX Designer',
      titleEn: 'UI/UX Designer',
      count: 1,
      salaryMin: 0,
      salaryMax: 0,
      phase: 1,
      employmentType: 'project-based',
      requirements: [
        '--- المؤهلات والخبرة ---',
        '4+ سنوات خبرة في تصميم UI/UX، ويفضل في مشاريع SaaS',
        'إتقان أدوات التصميم: Figma وAdobe XD',
        'خبرة مثبتة في تصميم SaaS Dashboards ولوحات التحكم المعقدة',
        'فهم متقدم لمبادئ UX وHuman-Centered Design',
        'خبرة في إنشاء Design Systems وComponent Libraries قابلة لإعادة الاستخدام',
        'معرفة معايير Accessibility (WCAG 2.1) وتطبيقها في التصميم',
        'خبرة في User Research وA/B Testing لتحسين واجهة وتجربة المستخدم',
        'Portfolio قوي يعرض مشاريع SaaS وواجهات معقدة',
        'فهم أساسي لتقنيات Frontend Development (HTML/CSS)',
        '',
        '--- المسؤوليات ---',
        'تصميم واجهات مستخدم مبتكرة وفعّالة لتطبيقات SaaS',
        'تطوير Design Systems وComponent Libraries لضمان اتساق التصميم',
        'تنفيذ مبادئ User Experience لتحسين تجربة المستخدم',
        'تصميم واجهات متوافقة مع Accessibility Standards (WCAG 2.1)',
        'إجراء اختبارات A/B Testing واختبارات المستخدم (User Testing & Research)',
        'التعاون مع فرق التطوير لضمان تنفيذ التصميم بدقة',
        'إعداد وتقديم Wireframes, Prototypes, وUser Flows للمشاريع الجديدة',
        'متابعة أحدث اتجاهات UI/UX لضمان تحديث المنصة بشكل مستمر',
        '',
        '--- ميزات إضافية ---',
        '⭐ القدرة على العمل في فرق Agile/Scrum',
        '⭐ مهارات تواصل قوية وقدرة على توضيح القرارات التصميمية',
        '⭐ شغف بابتكار حلول تصميمية مبتكرة وتجربة مستخدم سلسة'
      ],
      requirementsEn: [
        '--- Qualifications & Experience ---',
        '4+ years UI/UX design experience, preferably in SaaS projects',
        'Master design tools: Figma and Adobe XD',
        'Proven experience designing SaaS Dashboards and complex control panels',
        'Advanced understanding of UX principles and Human-Centered Design',
        'Experience creating reusable Design Systems and Component Libraries',
        'Knowledge of Accessibility standards (WCAG 2.1) and implementation in design',
        'Experience in User Research and A/B Testing to improve UI/UX',
        'Strong portfolio showcasing SaaS projects and complex interfaces',
        'Basic understanding of Frontend Development technologies (HTML/CSS)',
        '',
        '--- Responsibilities ---',
        'Design innovative and effective user interfaces for SaaS applications',
        'Develop Design Systems and Component Libraries to ensure design consistency',
        'Implement User Experience principles to improve user experience',
        'Design interfaces compliant with Accessibility Standards (WCAG 2.1)',
        'Conduct A/B Testing and User Testing & Research',
        'Collaborate with development teams to ensure accurate design implementation',
        'Prepare and present Wireframes, Prototypes, and User Flows for new projects',
        'Follow latest UI/UX trends to ensure continuous platform updates',
        '',
        '--- Plus Points ---',
        '⭐ Ability to work in Agile/Scrum teams',
        '⭐ Strong communication skills and ability to explain design decisions',
        '⭐ Passion for innovative design solutions and smooth user experience'
      ]
    },
    {
      title: 'Content Writers',
      titleEn: 'Content Writers',
      count: 2,
      salaryMin: 0,
      salaryMax: 0,
      phase: 2,
      employmentType: 'full-time',
      requirements: [
        '--- المؤهلات والخبرة ---',
        'خبرة عملية 2+ سنوات في كتابة المحتوى الرقمي باللغة العربية',
        'إتقان قواعد اللغة العربية والقدرة على التعبير بوضوح ودقة',
        'معرفة أساسيات SEO وممارساته لتحسين ترتيب المحتوى',
        'مهارات قوية في التحرير الذاتي ومراجعة مقالات الزملاء',
        'خبرة في كتابة المحتوى التقني أو التجاري أو كلاهما',
        'مهارات بحث وتحليل قوية لضمان مصداقية المعلومات',
        'اهتمام بالتفاصيل والدقة اللغوية في كل قطعة محتوى',
        'مهارات تواصل وتعاون ممتازة للعمل ضمن فريق',
        '',
        '--- المسؤوليات ---',
        'إنتاج محتوى مكتوب عالي الجودة ومتوافق مع قواعد اللغة العربية',
        'كتابة مقالات طويلة: 1500-2500 كلمة (12-20 مقال أسبوعيًا)',
        'أو كتابة مقالات متوسطة: 800-1500 كلمة (18-22 مقال أسبوعيًا)',
        'أو كتابة مقالات قصيرة: 500-800 كلمة (20-25 مقال أسبوعيًا)',
        'إجراء مراجعة ذاتية ومراجعة الزملاء (Peer Review) لضمان الجودة',
        'تحسين المحتوى وفق معايير SEO للكلمات المفتاحية المستهدفة',
        'البحث والتحليل لضمان دقة المعلومات وجودة المحتوى',
        'التعاون مع فرق التسويق والمحررين لضمان تناسق المحتوى',
        'متابعة الاتجاهات والمواضيع الجديدة في السوق',
        '',
        '--- ميزات إضافية ---',
        '⭐ القدرة على العمل وفق جداول زمنية ضيقة مع الحفاظ على الجودة',
        '⭐ معرفة أساسيات التسويق الرقمي ومبادئ المحتوى التسويقي',
        '⭐ القدرة على كتابة محتوى جذاب ومقنع يستهدف الجمهور المناسب'
      ],
      requirementsEn: [
        '--- Qualifications & Experience ---',
        '2+ years hands-on experience in digital content writing in Arabic',
        'Master Arabic grammar and ability to express clearly and accurately',
        'Knowledge of SEO fundamentals and practices to improve content ranking',
        'Strong self-editing and peer review skills',
        'Experience writing technical or business content or both',
        'Strong research and analysis skills to ensure information credibility',
        'Attention to detail and linguistic accuracy in every piece of content',
        'Excellent communication and collaboration skills for teamwork',
        '',
        '--- Responsibilities ---',
        'Produce high-quality written content compliant with Arabic grammar rules',
        'Write long-form articles: 1500-2500 words (12-20 articles weekly)',
        'Or write medium articles: 800-1500 words (18-22 articles weekly)',
        'Or write short articles: 500-800 words (20-25 articles weekly)',
        'Conduct self-review and peer review to ensure quality',
        'Optimize content according to SEO standards for target keywords',
        'Research and analyze to ensure information accuracy and content quality',
        'Collaborate with marketing teams and editors to ensure content consistency',
        'Follow trends and new topics in the market',
        '',
        '--- Plus Points ---',
        '⭐ Ability to work under tight deadlines while maintaining quality',
        '⭐ Knowledge of digital marketing basics and marketing content principles',
        '⭐ Ability to write engaging and persuasive content targeting the right audience'
      ]
    },
    {
      title: 'أخصائي SEO',
      titleEn: 'SEO Specialist',
      count: 1,
      salaryMin: 0,
      salaryMax: 0,
      phase: 2,
      employmentType: 'full-time',
      requirements: [
        '--- المؤهلات والخبرة ---',
        'خبرة عملية 4 سنوات أو أكثر في SEO',
        'خبرة متقدمة في On-Page, Off-Page & Technical SEO',
        'فهم قوي لخوارزميات Google وأفضل ممارسات SEO',
        'القدرة على تحليل البيانات واتخاذ قرارات مبنية على أرقام',
        '',
        '--- المسؤوليات الأساسية ---',
        '--- On-Page SEO ---',
        'تنفيذ وتحسين استراتيجيات On-Page SEO (Content Optimization, Keywords, Internal Linking, Meta Data)',
        'تحسين عناوين الصفحات (Title Tags)، الوصف (Meta Descriptions)، والـ Headers (H1-H6)',
        'تحسين بنية URL وهيكلة الموقع',
        'تحسين محتوى الصفحات لتحقيق أفضل ترتيب في محركات البحث',
        'تطبيق Schema Markup وStructured Data',
        'تحسين الصور (Image Optimization) مع ALT tags وضوغط الصور',
        '',
        '--- Off-Page SEO ---',
        'إدارة وتنفيذ استراتيجيات Off-Page SEO (Link Building, Outreach, Backlinks Analysis)',
        'بناء علاقات مع مواقع الويب والمدونات ذات الصلة',
        'تحليل وتحسين ملف الروابط الخلفية (Backlink Profile)',
        'مراقبة والاستجابة لـ Negative SEO إذا حدث',
        'إدارة حملات Guest Posting وContent Outreach',
        '',
        '--- Technical SEO ---',
        'التعامل المتقدم مع Technical SEO (Site Structure, Indexing, Crawling, Page Speed, Core Web Vitals)',
        'إعداد وتحسين ملفات robots.txt و XML sitemaps',
        'تحسين سرعة تحميل الموقع (Page Speed Optimization)',
        'تحسين Core Web Vitals (LCP, FID, CLS)',
        'ضمان Mobile-First Indexing والاستجابة للموبايل',
        'حل مشاكل الـ Indexing والـ Crawling',
        'تحسين بنية الموقع والـ Site Architecture',
        '',
        '--- التحليل والتقارير ---',
        'تحليل الأداء باستخدام أدوات SEO: Google Search Console, Google Analytics, Ahrefs, SEMrush',
        'إعداد تقارير دورية شاملة عن أداء SEO',
        'تتبع الترتيب (Rank Tracking) للكلمات المفتاحية المستهدفة',
        'تحليل المنافسين وتحديد فرص التحسين',
        'عمل SEO Audits دورية واقتراح حلول قابلة للتنفيذ',
        'متابعة التحديثات المستمرة في خوارزميات محركات البحث (Google Algorithm Updates)',
        'تطبيق التغييرات بناءً على البيانات والتحليل',
        '',
        '--- التنسيق والتعاون ---',
        'التعاون مع فريق المحتوى لتحسين المقالات والمنشورات',
        'العمل مع المطورين لتنفيذ التحسينات التقنية',
        'التنسيق مع فريق التسويق لتحقيق الأهداف المشتركة',
        '',
        '--- المهارات التقنية والأدوات ---',
        'خبرة متقدمة في أدوات SEO الأساسية:',
        'Google Search Console (متقدم)',
        'Google Analytics (GA4)',
        'Ahrefs أو SEMrush (أحدهم على الأقل)',
        'Screaming Frog أو أدوات Crawling مشابهة',
        'PageSpeed Insights و Core Web Vitals',
        'معرفة بـ Schema.org و Structured Data',
        'فهم لـ HTML, CSS, JavaScript (أساسي)',
        'خبرة في استخدام أدوات Link Building',
        '',
        '--- المهارات الشخصية ---',
        'مهارات تحليلية ممتازة',
        'القدرة على العمل بشكل مستقل وإدارة الأولويات',
        'الانتباه للتفاصيل والدقة',
        'مهارات تواصل ممتازة (كتابة وعرض)',
        'القدرة على شرح المفاهيم التقنية لغير المتخصصين',
        'مهارات حل المشكلات والتفكير الإبداعي',
        '',
        '--- اللغات ---',
        'إتقان اللغة العربية (شرط أساسي)',
        'إتقان اللغة الإنجليزية (مطلوب)',
        '',
        '--- ميزات إضافية ---',
        '⭐ خبرة في SEO للمحتوى العربي والسوق السعودي/الخليجي',
        '⭐ خبرة في SEO لـ E-commerce platforms (Shopify, WooCommerce, Salla, Zid)',
        '⭐ معرفة بـ Local SEO',
        '⭐ شهادات SEO (Google Analytics Certification, etc.)',
        '⭐ خبرة في استخدام أدوات AI لتحسين SEO',
        '⭐ خبرة في Python أو Scripting لـ SEO automation'
      ],
      requirementsEn: [
        '--- Qualifications & Experience ---',
        '4 years or more of hands-on SEO experience',
        'Advanced experience in On-Page, Off-Page & Technical SEO',
        'Strong understanding of Google algorithms and SEO best practices',
        'Ability to analyze data and make data-driven decisions',
        '',
        '--- Core Responsibilities ---',
        '--- On-Page SEO ---',
        'Execute and optimize On-Page SEO strategies (Content Optimization, Keywords, Internal Linking, Meta Data)',
        'Optimize page titles (Title Tags), descriptions (Meta Descriptions), and Headers (H1-H6)',
        'Optimize URL structure and site architecture',
        'Optimize page content to achieve best search engine rankings',
        'Implement Schema Markup and Structured Data',
        'Optimize images (Image Optimization) with ALT tags and image compression',
        '',
        '--- Off-Page SEO ---',
        'Manage and execute Off-Page SEO strategies (Link Building, Outreach, Backlinks Analysis)',
        'Build relationships with relevant websites and blogs',
        'Analyze and improve backlink profile',
        'Monitor and respond to Negative SEO if it occurs',
        'Manage Guest Posting campaigns and Content Outreach',
        '',
        '--- Technical SEO ---',
        'Advanced Technical SEO (Site Structure, Indexing, Crawling, Page Speed, Core Web Vitals)',
        'Setup and optimize robots.txt and XML sitemaps files',
        'Optimize page loading speed (Page Speed Optimization)',
        'Optimize Core Web Vitals (LCP, FID, CLS)',
        'Ensure Mobile-First Indexing and mobile responsiveness',
        'Resolve Indexing and Crawling issues',
        'Optimize site structure and Site Architecture',
        '',
        '--- Analysis & Reporting ---',
        'Analyze performance using SEO tools: Google Search Console, Google Analytics, Ahrefs, SEMrush',
        'Prepare comprehensive periodic SEO performance reports',
        'Track ranking (Rank Tracking) for target keywords',
        'Analyze competitors and identify improvement opportunities',
        'Conduct periodic SEO Audits and propose actionable solutions',
        'Monitor continuous updates in search engine algorithms (Google Algorithm Updates)',
        'Apply changes based on data and analysis',
        '',
        '--- Coordination & Collaboration ---',
        'Collaborate with content team to optimize articles and posts',
        'Work with developers to implement technical improvements',
        'Coordinate with marketing team to achieve shared goals',
        '',
        '--- Technical Skills & Tools ---',
        'Advanced experience with essential SEO tools:',
        'Google Search Console (advanced)',
        'Google Analytics (GA4)',
        'Ahrefs or SEMrush (at least one)',
        'Screaming Frog or similar crawling tools',
        'PageSpeed Insights and Core Web Vitals',
        'Knowledge of Schema.org and Structured Data',
        'Understanding of HTML, CSS, JavaScript (basic)',
        'Experience using Link Building tools',
        '',
        '--- Soft Skills ---',
        'Excellent analytical skills',
        'Ability to work independently and manage priorities',
        'Attention to detail and accuracy',
        'Excellent communication skills (writing and presentation)',
        'Ability to explain technical concepts to non-specialists',
        'Problem-solving and creative thinking skills',
        '',
        '--- Languages ---',
        'Fluent in Arabic (essential)',
        'Fluent in English (required)',
        '',
        '--- Plus Points ---',
        '⭐ Experience in SEO for Arabic content and Saudi/GCC market',
        '⭐ Experience in SEO for E-commerce platforms (Shopify, WooCommerce, Salla, Zid)',
        '⭐ Knowledge of Local SEO',
        '⭐ SEO certifications (Google Analytics Certification, etc.)',
        '⭐ Experience using AI tools for SEO optimization',
        '⭐ Experience in Python or Scripting for SEO automation'
      ]
    },
    {
      title: 'كاتب محتوى',
      titleEn: 'Content Writer',
      count: 1,
      salaryMin: 0,
      salaryMax: 0,
      phase: 2,
      employmentType: 'full-time',
      requirements: [
        '--- المؤهلات والخبرة ---',
        'خبرة عملية لا تقل عن سنتين في كتابة المحتوى',
        'خبرة سابقة في السوق الخليجي (شرط أساسي)',
        'وجود Portfolio / Samples واضح يظهر جودة العمل (شرط أساسي)',
        'خبرة في كتابة محتوى تسويقي للعلامات التجارية',
        '',
        '--- المسؤوليات الأساسية ---',
        '--- إنشاء المحتوى ---',
        'كتابة محتوى احترافي يناسب طبيعة الجمهور الخليجي (Saudi, UAE, Kuwait, etc.)',
        'كتابة محتوى تسويقي متعدد الأشكال:',
        'Social Media: منشورات، قصص، محتوى تفاعلي',
        'Websites: صفحات المنتج، صفحات الهبوط (Landing Pages)',
        'Ads: نصوص إعلانية لـ Google Ads, Meta Ads, LinkedIn Ads',
        'Blogs: مقالات SEO-friendly للمدونة',
        'الكتابة بأسلوب احترافي مناسب للعلامات التجارية',
        'الالتزام بـ Tone of Voice الخاص بالبراند والحفاظ على الاتساق',
        'كتابة محتوى يراعي SEO (SEO-aware content) مع دمج الكلمات المفتاحية بشكل طبيعي',
        '',
        '--- مراجعة وتحرير ---',
        'مراجعة وتحرير المحتوى لضمان الجودة والدقة اللغوية',
        'التأكد من خلو المحتوى من الأخطاء الإملائية والنحوية',
        'ضمان الاتساق في الأسلوب والشكل',
        'التحقق من دقة المعلومات والوقائع',
        '',
        '--- التعاون والتنسيق ---',
        'التعاون مع فريق التسويق لتحقيق أهداف الحملات',
        'العمل مع SEO Specialist لتحسين المقالات للمحركات البحث',
        'التنسيق مع فريق التصميم لإنشاء محتوى متكامل',
        'المشاركة في اجتماعات التخطيط وBrainstorming sessions',
        'الالتزام بالمواعيد النهائية والعمل ضمن فريق',
        '',
        '--- البحث والفهم ---',
        'البحث المستمر عن الموضوعات والاتجاهات في السوق الخليجي',
        'فهم عميق لثقافة الجمهور المستهدف وتفضيلاته',
        'تحليل المحتوى المنافس وتحديد فرص التحسين',
        'البقاء محدثاً بآخر الاتجاهات في التسويق الرقمي والمحتوى',
        '',
        '--- المهارات الكتابية ---',
        'مهارات كتابة ممتازة باللغة العربية',
        'مهارات كتابة جيدة باللغة الإنجليزية',
        'القدرة على التكيف مع أنماط كتابة مختلفة حسب العلامة التجارية',
        'فهم عميق للغة التسويق والإقناع (Copywriting)',
        'القدرة على كتابة محتوى جذاب ومقنع',
        'مهارات البحث وجمع المعلومات',
        '',
        '--- المعرفة المتخصصة ---',
        'فهم عميق لثقافة السوق الخليجي وعادات المستهلكين',
        'معرفة بمنصات التواصل الاجتماعي وأفضل الممارسات',
        'فهم أساسي لـ SEO وكتابة المحتوى المحسّن للمحركات البحث',
        'معرفة بأساسيات التسويق الرقمي',
        '',
        '--- المهارات الشخصية ---',
        'الالتزام بالمواعيد والعمل ضمن فريق',
        'القدرة على العمل تحت ضغط',
        'الانتباه للتفاصيل والدقة',
        'مهارات تواصل جيدة',
        'الإبداع والتفكير الإبداعي',
        'القدرة على تلقي وتطبيق الملاحظات (Feedback)',
        '',
        '--- اللغات ---',
        'إتقان اللغة العربية (شرط أساسي جداً)',
        'إتقان اللغة الإنجليزية (مطلوب)',
        '',
        '--- ميزات إضافية ---',
        '⭐ خبرة في كتابة محتوى لـ E-commerce أو SaaS companies',
        '⭐ خبرة في كتابة محتوى تقني أو B2B',
        '⭐ معرفة بأدوات AI للكتابة (ChatGPT, Jasper, etc.)',
        '⭐ مهارات في التصميم الأساسي (Canva, Adobe)',
        '⭐ معرفة بـ CMS platforms (WordPress, etc.)',
        '⭐ خبرة في إدارة المحتوى على منصات التواصل الاجتماعي'
      ],
      requirementsEn: [
        '--- Qualifications & Experience ---',
        'Minimum 2 years of hands-on content writing experience',
        'Previous experience in GCC market (essential requirement)',
        'Clear Portfolio / Samples demonstrating work quality (essential requirement)',
        'Experience writing marketing content for brands',
        '',
        '--- Core Responsibilities ---',
        '--- Content Creation ---',
        'Write professional content suitable for GCC audience nature (Saudi, UAE, Kuwait, etc.)',
        'Write multi-format marketing content:',
        'Social Media: Posts, stories, interactive content',
        'Websites: Product pages, landing pages',
        'Ads: Ad copy for Google Ads, Meta Ads, LinkedIn Ads',
        'Blogs: SEO-friendly articles for the blog',
        'Write in professional style suitable for brands',
        'Maintain brand Tone of Voice and consistency',
        'Write SEO-aware content with natural keyword integration',
        '',
        '--- Review & Editing ---',
        'Review and edit content to ensure quality and linguistic accuracy',
        'Ensure content is free from spelling and grammatical errors',
        'Ensure consistency in style and format',
        'Verify accuracy of information and facts',
        '',
        '--- Collaboration & Coordination ---',
        'Collaborate with marketing team to achieve campaign goals',
        'Work with SEO Specialist to optimize articles for search engines',
        'Coordinate with design team to create integrated content',
        'Participate in planning meetings and brainstorming sessions',
        'Meet deadlines and work within a team',
        '',
        '--- Research & Understanding ---',
        'Continuous research on topics and trends in GCC market',
        'Deep understanding of target audience culture and preferences',
        'Analyze competitor content and identify improvement opportunities',
        'Stay updated with latest trends in digital marketing and content',
        '',
        '--- Writing Skills ---',
        'Excellent Arabic writing skills',
        'Good English writing skills',
        'Ability to adapt to different writing styles according to brand',
        'Deep understanding of marketing language and persuasion (Copywriting)',
        'Ability to write engaging and persuasive content',
        'Research and information gathering skills',
        '',
        '--- Specialized Knowledge ---',
        'Deep understanding of GCC market culture and consumer habits',
        'Knowledge of social media platforms and best practices',
        'Basic understanding of SEO and search engine optimized content writing',
        'Knowledge of digital marketing fundamentals',
        '',
        '--- Soft Skills ---',
        'Meeting deadlines and working within a team',
        'Ability to work under pressure',
        'Attention to detail and accuracy',
        'Good communication skills',
        'Creativity and creative thinking',
        'Ability to receive and apply feedback',
        '',
        '--- Languages ---',
        'Fluent in Arabic (highly essential)',
        'Fluent in English (required)',
        '',
        '--- Plus Points ---',
        '⭐ Experience writing content for E-commerce or SaaS companies',
        '⭐ Experience writing technical or B2B content',
        '⭐ Knowledge of AI writing tools (ChatGPT, Jasper, etc.)',
        '⭐ Basic design skills (Canva, Adobe)',
        '⭐ Knowledge of CMS platforms (WordPress, etc.)',
        '⭐ Experience managing content on social media platforms'
      ]
    },
    // ========== OPERATIONS & SUPPORT (Phase 3) ==========
    {
      title: 'مدير حسابات',
      titleEn: 'Account Manager',
      count: 1,
      salaryMin: 0,
      salaryMax: 0,
      phase: 3,
      employmentType: 'full-time',
      requirements: [
        '--- المؤهلات والخبرة ---',
        'خبرة عملية لا تقل عن سنة واحدة كمدير حسابات أو دور مشابه في إدارة العملاء',
        'خلفية قوية في التسويق (Digital Marketing / Campaign Management / Marketing Strategy)',
        'فهم عميق للـ operations وإدارة العمليات الداخلية',
        '',
        '--- المسؤوليات الأساسية ---',
        'إدارة والتواصل المستمر مع العملاء (Client Relationship Management)',
        'فهم متطلبات العملاء وتحويلها إلى خطط تنفيذ واضحة وقابلة للقياس',
        'التنسيق بين فرق التسويق والتنفيذ والعمليات لضمان التكامل والجودة',
        'متابعة الأداء، المواعيد النهائية، وجودة التسليم للعملاء',
        'إعداد التقارير الدورية للعملاء والإدارة العليا',
        'المساهمة في تحسين الـ workflows والعمليات الداخلية باستمرار',
        'إدارة التوقعات وضمان رضا العملاء على المدى الطويل',
        'التعامل مع التحديات والاستفسارات من العملاء بطريقة احترافية',
        'تنسيق الاجتماعات الدورية والـ check-ins مع العملاء',
        'تحليل أداء الحسابات وتحديد فرص النمو والتحسين',
        '',
        '--- المهارات التقنية ---',
        'إتقان أدوات إدارة المشاريع (Project Management Tools): Notion, Trello, Asana, Monday.com',
        'خبرة في أدوات التواصل والعروض: Slack, Microsoft Teams, Google Workspace',
        'فهم أساسي لأدوات التحليلات: Google Analytics, CRM systems',
        'معرفة بأدوات التسويق الرقمي الأساسية',
        '',
        '--- المهارات الشخصية ---',
        'مهارات تواصل وتنظيم عالية جداً',
        'القدرة على العمل تحت ضغط وإدارة أكثر من حساب في نفس الوقت',
        'مهارات حل المشكلات والتفكير التحليلي',
        'القدرة على بناء علاقات طويلة المدى مع العملاء',
        'مهارات التفاوض وإدارة التوقعات',
        'الانتباه للتفاصيل والدقة في التنفيذ',
        'مهارات العرض والتقديم (Presentation Skills)',
        'القدرة على العمل بشكل تعاوني مع فرق متعددة',
        '',
        '--- اللغات ---',
        'إتقان اللغة العربية (شرط أساسي)',
        'إتقان اللغة الإنجليزية (مطلوب)',
        '',
        '--- ميزات إضافية ---',
        '⭐ خبرة في العمل مع شركات SaaS أو B2B',
        '⭐ خبرة في السوق السعودي أو الخليجي',
        '⭐ شهادات في إدارة المشاريع (PMP, Agile)',
        '⭐ خبرة في استخدام أدوات CRM متقدمة',
        '⭐ فهم أساسي لـ SEO و Digital Marketing metrics'
      ],
      requirementsEn: [
        '--- Qualifications & Experience ---',
        'Minimum 1 year of hands-on experience as Account Manager or similar client management role',
        'Strong background in marketing (Digital Marketing / Campaign Management / Marketing Strategy)',
        'Deep understanding of operations and internal processes management',
        '',
        '--- Core Responsibilities ---',
        'Manage and maintain continuous communication with clients (Client Relationship Management)',
        'Understand client requirements and translate them into clear, measurable execution plans',
        'Coordinate between marketing, execution, and operations teams to ensure integration and quality',
        'Monitor performance, deadlines, and delivery quality for clients',
        'Prepare periodic reports for clients and senior management',
        'Continuously contribute to improving workflows and internal processes',
        'Manage expectations and ensure long-term client satisfaction',
        'Handle challenges and client inquiries professionally',
        'Coordinate regular meetings and check-ins with clients',
        'Analyze account performance and identify growth and improvement opportunities',
        '',
        '--- Technical Skills ---',
        'Proficiency in Project Management Tools: Notion, Trello, Asana, Monday.com',
        'Experience with communication and presentation tools: Slack, Microsoft Teams, Google Workspace',
        'Basic understanding of analytics tools: Google Analytics, CRM systems',
        'Knowledge of basic digital marketing tools',
        '',
        '--- Soft Skills ---',
        'Excellent communication and organizational skills',
        'Ability to work under pressure and manage multiple accounts simultaneously',
        'Problem-solving and analytical thinking skills',
        'Ability to build long-term relationships with clients',
        'Negotiation skills and expectation management',
        'Attention to detail and execution accuracy',
        'Presentation skills',
        'Ability to work collaboratively with multiple teams',
        '',
        '--- Languages ---',
        'Fluent in Arabic (essential)',
        'Fluent in English (required)',
        '',
        '--- Plus Points ---',
        '⭐ Experience working with SaaS or B2B companies',
        '⭐ Experience in Saudi or GCC market',
        '⭐ Project management certifications (PMP, Agile)',
        '⭐ Experience with advanced CRM tools',
        '⭐ Basic understanding of SEO and Digital Marketing metrics'
      ]
    },
    // ========== SALES & MARKETING (Phase 4) ==========
    {
      title: 'ممثل مبيعات - ميداني',
      titleEn: 'Sales Representative - Offline',
      count: 1,
      salaryMin: 0,
      salaryMax: 0,
      phase: 4,
      employmentType: 'full-time',
      requirements: [
        '--- المؤهلات والخبرة ---',
        '3+ سنوات خبرة مثبتة في مبيعات B2B أو SaaS',
        'سجل قوي في تحقيق أو تجاوز أهداف المبيعات',
        'خبرة في استخدام CRM وأنظمة إدارة العملاء',
        'مهارات تواصل، إقناع، وتفاوض استثنائية',
        'فهم شامل لنماذج الأعمال SaaS والاشتراكات',
        'القدرة على العمل تحت ضغط وتحقيق أهداف شهرية متكررة',
        'إتقان اللغة العربية والإنجليزية',
        '',
        '--- المسؤوليات ---',
        'إدارة عملية المبيعات من البداية حتى الإغلاق ضمن أهداف شهرية محددة',
        'التواصل مع العملاء المحتملين وإجراء عروض تقديمية فعّالة',
        'إدارة علاقات العملاء باستخدام CRM مثل Salesforce، HubSpot، Pipedrive',
        'فهم دورة حياة المبيعات الخاصة بمنصات SaaS ونماذج الاشتراكات',
        'تقديم حلول مخصصة تلبي احتياجات العملاء ومتطلباتهم',
        'التعاون مع فرق التسويق والدعم لضمان تجربة عميل ممتازة',
        'متابعة مؤشرات الأداء ورفع تقارير دقيقة للإدارة',
        'بناء شبكة علاقات قوية مع أصحاب المتاجر والعملاء المحتملين',
        '',
        '--- ميزات إضافية ---',
        '⭐ القدرة على التعلم السريع عن المنتجات والخدمات التقنية',
        '⭐ مهارات تقديم عروض رقمية وفعالة للعملاء',
        '⭐ شغف بالتعامل مع عملاء المتاجر الإلكترونية وتوسيع قاعدة العملاء'
      ],
      requirementsEn: [
        '--- Qualifications & Experience ---',
        '3+ years proven B2B or SaaS sales experience',
        'Strong track record achieving or exceeding sales targets',
        'Experience using CRM and customer management systems',
        'Exceptional communication, persuasion, and negotiation skills',
        'Comprehensive understanding of SaaS business models and subscriptions',
        'Ability to work under pressure and achieve recurring monthly targets',
        'Fluent in Arabic and English',
        '',
        '--- Responsibilities ---',
        'Manage sales process from start to close within set monthly targets',
        'Communicate with potential clients and conduct effective presentations',
        'Manage customer relationships using CRM like Salesforce, HubSpot, Pipedrive',
        'Understand SaaS platform sales lifecycle and subscription models',
        'Provide customized solutions meeting customer needs and requirements',
        'Collaborate with marketing and support teams to ensure excellent customer experience',
        'Track KPIs and provide accurate reports to management',
        'Build strong network with store owners and potential customers',
        '',
        '--- Plus Points ---',
        '⭐ Quick learning ability for technical products and services',
        '⭐ Digital and effective customer presentation skills',
        '⭐ Passion for dealing with e-commerce clients and expanding customer base'
      ]
    },
    {
      title: 'ممثل مبيعات - هاتفي',
      titleEn: 'Sales Representative - Telesales',
      count: 1,
      salaryMin: 0,
      salaryMax: 0,
      phase: 4,
      employmentType: 'full-time',
      requirements: [
        '--- المؤهلات والخبرة ---',
        '3+ سنوات خبرة مثبتة في مبيعات B2B أو SaaS عبر الهاتف',
        'سجل قوي في تحقيق أو تجاوز أهداف المبيعات الهاتفية',
        'خبرة في استخدام CRM وأنظمة إدارة العملاء',
        'مهارات تواصل هاتفي، إقناع، وتفاوض استثنائية',
        'فهم شامل لنماذج الأعمال SaaS والاشتراكات',
        'القدرة على العمل تحت ضغط وتحقيق أهداف شهرية متكررة',
        'إتقان اللغة العربية والإنجليزية',
        '',
        '--- المسؤوليات ---',
        'إدارة عملية المبيعات الهاتفية من البداية حتى الإغلاق',
        'إجراء مكالمات باردة (Cold Calls) وتحويلها لعملاء محتملين',
        'إدارة علاقات العملاء باستخدام CRM مثل Salesforce، HubSpot، Pipedrive',
        'متابعة العملاء المحتملين عبر المكالمات والإيميلات',
        'تقديم عروض المنتج وشرح المزايا بشكل فعّال عبر الهاتف',
        'تحقيق أهداف المبيعات اليومية والشهرية',
        'تسجيل جميع المكالمات والتفاعلات في نظام CRM',
        'التعاون مع فريق المبيعات الميداني لتحويل العملاء المحتملين',
        '',
        '--- ميزات إضافية ---',
        '⭐ خبرة في استخدام أدوات الاتصال الآلي وDialers',
        '⭐ مهارات بناء علاقات سريعة عبر الهاتف',
        '⭐ قدرة على التعامل مع الاعتراضات وتحويلها لفرص'
      ],
      requirementsEn: [
        '--- Qualifications & Experience ---',
        '3+ years proven B2B or SaaS telesales experience',
        'Strong track record achieving or exceeding phone sales targets',
        'Experience using CRM and customer management systems',
        'Exceptional phone communication, persuasion, and negotiation skills',
        'Comprehensive understanding of SaaS business models and subscriptions',
        'Ability to work under pressure and achieve recurring monthly targets',
        'Fluent in Arabic and English',
        '',
        '--- Responsibilities ---',
        'Manage telesales process from start to close',
        'Conduct cold calls and convert them to potential customers',
        'Manage customer relationships using CRM like Salesforce, HubSpot, Pipedrive',
        'Follow up with potential customers via calls and emails',
        'Present product offerings and explain benefits effectively over phone',
        'Achieve daily and monthly sales targets',
        'Log all calls and interactions in CRM system',
        'Collaborate with field sales team to convert leads',
        '',
        '--- Plus Points ---',
        '⭐ Experience with auto-dialing tools and Dialers',
        '⭐ Quick relationship building skills over phone',
        '⭐ Ability to handle objections and turn them into opportunities'
      ]
    },
    {
      title: 'أخصائي تسويق رقمي',
      titleEn: 'Digital Marketing Specialist',
      count: 1,
      salaryMin: 0,
      salaryMax: 0,
      phase: 4,
      employmentType: 'full-time',
      requirements: [
        '--- المؤهلات والخبرة ---',
        '2-3 سنوات خبرة عملية في التسويق الرقمي، مع تفضيل خبرة في تسويق SaaS أو B2B',
        'خبرة مؤكدة في إدارة وتنفيذ حملات Google Ads (Search، Display، Shopping)',
        'خبرة في إدارة حملات Meta Ads (Facebook & Instagram Ads) وتحسين الأداء',
        'معرفة عملية في SEO/SEM، بحث الكلمات المفتاحية، وتحسين محركات البحث',
        'خبرة في إدارة حسابات وسائل التواصل الاجتماعي (LinkedIn، Twitter/X، Instagram، Facebook)',
        'مهارات تحليل بيانات متقدمة وإتقان Google Analytics 4 (GA4)',
        'خبرة في إنشاء محتوى تسويقي فعّال وإدارة التقويم التحريري',
        'إتقان أدوات التسويق: Google Ads Editor، Meta Business Suite، Hootsuite/Buffer',
        'فهم عميق لـ Email Marketing، بناء قوائم البريد، وتحسين معدلات الفتح والنقر',
        'معرفة بـ A/B Testing وتحسين معدلات التحويل (CRO)',
        'مهارات قوية في الكتابة التسويقية والإبداعية بالعربية والإنجليزية',
        'فهم أساسيات مقاييس التسويق: CAC، ROI، CPA، Conversion Rate',
        'مهارات حل المشاكل والقدرة على تحليل التحديات التسويقية وإيجاد حلول فعالة',
        'معرفة باستخدام أدوات الذكاء الاصطناعي لتوليد الصور (AI Image Generation Tools)',
        'إتقان اللغة العربية والإنجليزية كتابةً وتحدثاً',
        '',
        '--- المسؤوليات ---',
        'إدارة وتنفيذ حملات إعلانية مدفوعة على Google Ads وMeta Ads ضمن الميزانيات المخصصة',
        'تحليل أداء الحملات باستمرار، تحسين الاستهداف، وتحقيق أفضل ROI',
        'إدارة حسابات وسائل التواصل الاجتماعي وإنشاء محتوى تفاعلي وجذاب',
        'تطوير وتنفيذ استراتيجيات SEO/SEM لتحسين الظهور العضوي والمدفوع',
        'إجراء بحث الكلمات المفتاحية وتحسين محتوى الموقع والمقالات لتحسين الترتيب',
        'إنشاء تقارير أسبوعية وشهرية شاملة عن أداء الحملات والمقاييس الرئيسية',
        'إدارة الميزانيات الإعلانية بفعالية وتحسين توزيع الإنفاق عبر القنوات',
        'إنشاء وإدارة حملات Email Marketing وDrip Campaigns لتحويل العملاء المحتملين',
        'إدارة التقويم التحريري والجدولة الزمنية للنشر عبر جميع القنوات',
        'مراقبة وتحليل استراتيجيات المنافسين لتحديد فرص التحسين',
        'إجراء اختبارات A/B على الإعلانات والمحتوى لتحسين الأداء',
        'التعاون الوثيق مع فرق المبيعات والمحتوى والتصميم لتحقيق الأهداف التسويقية',
        'إدارة وتحسين Landing Pages لتحسين معدلات التحويل',
        '',
        '--- ميزات إضافية ---',
        '⭐ خبرة عملية في تسويق منتجات SaaS أو B2B',
        '⭐ إتقان أدوات التحليل المتقدمة (Google Tag Manager، Hotjar، Mixpanel)',
        '⭐ شهادات Google Ads وMeta Ads الرسمية',
        '⭐ مهارات في التصميم الأساسي (Canva، Adobe Express)',
        '⭐ خبرة في إدارة محتوى WordPress أو أنظمة CMS أخرى',
        '⭐ معرفة بأدوات التسويق الآلي (HubSpot، ActiveCampaign، Mailchimp)',
        '⭐ خبرة في تحليل سلوك المستخدم (User Behavior Analysis)',
        '⭐ مهارات في إنشاء وتحرير الفيديوهات القصيرة للمنصات الاجتماعية'
      ],
      requirementsEn: [
        '--- Qualifications & Experience ---',
        '2-3 years hands-on experience in digital marketing, preferably in SaaS or B2B marketing',
        'Proven experience managing and executing Google Ads campaigns (Search, Display, Shopping)',
        'Experience managing Meta Ads (Facebook & Instagram Ads) and performance optimization',
        'Practical knowledge of SEO/SEM, keyword research, and search engine optimization',
        'Experience managing social media accounts (LinkedIn, Twitter/X, Instagram, Facebook)',
        'Advanced data analysis skills and Google Analytics 4 (GA4) proficiency',
        'Experience creating effective marketing content and managing editorial calendars',
        'Proficiency with marketing tools: Google Ads Editor, Meta Business Suite, Hootsuite/Buffer',
        'Deep understanding of Email Marketing, list building, and open/click rate optimization',
        'Knowledge of A/B Testing and Conversion Rate Optimization (CRO)',
        'Strong marketing and creative writing skills in Arabic and English',
        'Understanding of marketing metrics fundamentals: CAC, ROI, CPA, Conversion Rate',
        'Problem-solving skills and ability to analyze marketing challenges and find effective solutions',
        'Knowledge of using AI tools for image generation (AI Image Generation Tools)',
        'Fluent in Arabic and English (written and spoken)',
        '',
        '--- Responsibilities ---',
        'Manage and execute paid advertising campaigns on Google Ads and Meta Ads within allocated budgets',
        'Continuously analyze campaign performance, optimize targeting, and achieve best ROI',
        'Manage social media accounts and create engaging, interactive content',
        'Develop and execute SEO/SEM strategies to improve organic and paid visibility',
        'Conduct keyword research and optimize website and article content for better rankings',
        'Create comprehensive weekly and monthly reports on campaign performance and key metrics',
        'Manage advertising budgets effectively and optimize spending distribution across channels',
        'Create and manage Email Marketing campaigns and Drip Campaigns to convert leads',
        'Manage editorial calendars and scheduling across all channels',
        'Monitor and analyze competitor strategies to identify improvement opportunities',
        'Conduct A/B tests on ads and content to improve performance',
        'Work closely with sales, content, and design teams to achieve marketing goals',
        'Manage and optimize Landing Pages to improve conversion rates',
        '',
        '--- Plus Points ---',
        '⭐ Hands-on experience marketing SaaS or B2B products',
        '⭐ Proficiency with advanced analytics tools (Google Tag Manager, Hotjar, Mixpanel)',
        '⭐ Google Ads and Meta Ads official certifications',
        '⭐ Basic design skills (Canva, Adobe Express)',
        '⭐ Experience managing WordPress content or other CMS platforms',
        '⭐ Knowledge of marketing automation tools (HubSpot, ActiveCampaign, Mailchimp)',
        '⭐ Experience in User Behavior Analysis',
        '⭐ Skills in creating and editing short-form videos for social platforms'
      ]
    },
  ];
}

